# Generated by Django 4.2.24 on 2025-09-14 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_percent'], name='shop_produc_discoun_bb2b3c_idx'),
        ),
    ]
